# Generated by Django 5.2.4 on 2025-08-05 23:12

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_area',
        ),
        migrations.AddField(
            model_name='service',
            name='service_radius',
            field=models.PositiveIntegerField(default=20, help_text='Service coverage radius in kilometers'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT(0 0)', geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT(0 0)', geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT(0 0)', geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT(0 0)', geography=True, srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='SRID=4326;POINT(0 0)', upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
